=== ChristianFrisson/FUBIOSC/Fubi/FubiRecognizers.dtd
<!ELEMENT FubiRecognizers (JointRelationRecognizer|JointOrientationRecognizer|LinearMovementRecognizer|FingerCountRecognizer|CombinationRecognizer)+>
  <!ATTLIST FubiRecognizers
    globalMinConfidence CDATA #IMPLIED>

<!ENTITY % joints "(head | neck | torso | waist |	leftShoulder | leftElbow | leftWrist | leftHand | rightShoulder |	rightElbow | rightWrist | rightHand |	leftHip |	leftKnee |	leftAnkle |	leftFoot | rightHip | rightKnee | rightAnkle | rightFoot)">
<!ENTITY % measures "(millimeter | bodyHeight | torsoHeight | shoulderWidth | hipWidth | armLength | upperArmLength | lowerArmLength | legLength | upperLegLength | lowerLegLength)">

<!ELEMENT JointRelationRecognizer (Joints, (((MaxValues, MinValues?)|(MinValues, MaxValues?))|Relation+), METAINFO?)>
  <!ATTLIST JointRelationRecognizer
    name ID #REQUIRED
    visibility (visible|hidden) 'visible'
    useLocalPositions (true|false) 'false'
    minConfidence CDATA #IMPLIED
    measuringUnit %measures; 'millimeter'>
  <!ELEMENT Joints EMPTY>
  <!ATTLIST Joints
    main %joints; #REQUIRED
    relative %joints; #IMPLIED>
  <!ELEMENT MaxValues EMPTY>
  <!ATTLIST MaxValues
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    z CDATA #IMPLIED
    dist CDATA #IMPLIED>
  <!ELEMENT MinValues EMPTY>
  <!ATTLIST MinValues
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    z CDATA #IMPLIED
    dist CDATA #IMPLIED>
  <!ELEMENT Relation EMPTY>
  <!ATTLIST Relation
    type (inFrontOf|behind|leftOf|rightOf|above|below|apartOf) #REQUIRED
    min CDATA '0'
    max CDATA #IMPLIED>

<!ELEMENT JointOrientationRecognizer (Joint, ((MaxDegrees, MinDegrees?)|(MinDegrees, MaxDegrees?)), METAINFO?)>
  <!ATTLIST JointOrientationRecognizer
    name ID #REQUIRED
    visibility (visible|hidden) 'visible'
    useLocalOrientations (true|false) 'true'
    minConfidence CDATA #IMPLIED>
  <!ELEMENT Joint EMPTY>
    <!ATTLIST Joint name %joints; #REQUIRED>
  <!ELEMENT MaxDegrees EMPTY>
    <!ATTLIST MaxDegrees
      x CDATA #IMPLIED
      y CDATA #IMPLIED
      z CDATA #IMPLIED>
  <!ELEMENT MinDegrees EMPTY>
    <!ATTLIST MinDegrees 
      x CDATA #IMPLIED
      y CDATA #IMPLIED
      z CDATA #IMPLIED>

<!ELEMENT LinearMovementRecognizer (Joints, (Direction|BasicDirection)?, Speed, METAINFO?)>
  <!ATTLIST LinearMovementRecognizer
    name ID #REQUIRED
    visibility (visible|hidden) 'visible'
    useLocalPositions (true|false) 'false'
    minConfidence CDATA #IMPLIED
    useOnlyCorrectDirectionComponent (true|false) 'true'>
  <!ELEMENT Direction EMPTY>
    <!ATTLIST Direction
      x CDATA #REQUIRED
      y CDATA #REQUIRED
      z CDATA #REQUIRED
      maxAngleDifference CDATA '45.0'>
<!ELEMENT BasicDirection EMPTY>
 <!ATTLIST BasicDirection
      type (left|right|up|down|forward|backward|anyDirection) #REQUIRED
      maxAngleDifference CDATA '45.0'>
  <!ELEMENT Speed EMPTY>
    <!ATTLIST Speed
      min CDATA #IMPLIED
      max CDATA #IMPLIED>

<!ELEMENT FingerCountRecognizer (Joint, FingerCount, METAINFO?)>
  <!ATTLIST FingerCountRecognizer
    name ID #REQUIRED
    visibility (visible|hidden) 'visible'
    minConfidence CDATA #IMPLIED>
  <!ELEMENT FingerCount EMPTY>
    <!ATTLIST FingerCount
      min (0|1|2|3|4|5) '0'
      max (0|1|2|3|4|5) '5'
      useMedianCalculation (true|false) 'false'>
    
<!ELEMENT CombinationRecognizer ((State)+, METAINFO?)>
  <!ATTLIST CombinationRecognizer name ID #REQUIRED
    waitUntilLastStateRecognizersStop (true|false) 'false'>
  <!ELEMENT State ((Recognizer|NotRecognizer)+, AlternativeRecognizers?)>
    <!ATTLIST State
      minDuration CDATA '0'
      maxDuration CDATA '-1'
      timeForTransition CDATA '1'
      maxInterruptionTime CDATA #IMPLIED
      noInterrruptionBeforeMinDuration (true|false) 'false'>
    <!ELEMENT Recognizer EMPTY>
      <!ATTLIST Recognizer 
        name CDATA #REQUIRED
        minConfidence CDATA #IMPLIED
        ignoreOnTrackingError (true|false) 'false'>
    <!ELEMENT NotRecognizer EMPTY>
    <!ATTLIST NotRecognizer 
        name CDATA #REQUIRED
        minConfidence CDATA #IMPLIED
        ignoreOnTrackingError (true|false) 'true'>
    <!ELEMENT AlternativeRecognizers (Recognizer|NotRecognizer)+>

<!ELEMENT METAINFO EMPTY>

=== ChristianFrisson/FUBIOSC/bin/MouseControlRecognizers.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE FubiRecognizers PUBLIC "-//Human Centered Multimedia Lab - Augsburg University//DTD FubiRecognizers V 0.5//EN" "http://hcm-lab.de/downloads/FubiRecognizers.dtd">
<FubiRecognizers>
  <LinearMovementRecognizer name="mouseClick">
    <Joints main="rightHand" relative="rightShoulder"/>
    <Direction x="0" y="0" z="-1"/>
    <Speed min="2000"/>
  </LinearMovementRecognizer>
  <LinearMovementRecognizer name="mouseClick1">
    <Joints main="leftHand" relative="leftShoulder"/>
    <Direction x="0" y="-1" z="0"/>
    <Speed min="2000"/>
  </LinearMovementRecognizer>
</FubiRecognizers>

=== ChristianFrisson/FUBIOSC/bin/LegPostureRecognizers.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE FubiRecognizers PUBLIC "-//Human Centered Multimedia Lab - Augsburg University//DTD FubiRecognizers V 0.5//EN" "http://hcm-lab.de/downloads/FubiRecognizers.dtd">
<FubiRecognizers>
  <!-- EXPO-standing scheme for coding standing leg posture (only OpenNI compatible parts) -->
  
  <!-- left/right leg shapes -->
  <JointRelationRecognizer name="LegShapeCrossed">
    <Joints main="rightFoot" relative="leftFoot"/>
    <MaxValues x="0"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="LegShapeClosed">
    <Joints main="rightFoot" relative="leftFoot"/>
    <MinValues x="5"/>
    <MaxValues x="150"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="LegShapeNormal">
    <Joints main="rightFoot" relative="leftFoot"/>
    <MinValues x="151"/>
    <MaxValues x="300"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="LegShapeApart">
    <Joints main="rightFoot" relative="leftFoot"/>
    <MinValues x="301"/>
  </JointRelationRecognizer>

  <!-- right knee shape -->
  <JointOrientationRecognizer name="RightKneeShapeNormal">
    <Joint name="rightKnee"/>
    <MinDegrees x="-20"/>
  </JointOrientationRecognizer>
  <JointOrientationRecognizer name="RightKneeShapeSlightlyFlexed">
    <Joint name="rightKnee"/>
    <MaxDegrees x="-20.01"/>
    <MinDegrees x="-40"/>
  </JointOrientationRecognizer>
  <JointOrientationRecognizer name="RightKneeShapeFlexed">
    <Joint name="rightKnee"/>
    <MaxDegrees x="-40.01"/>
  </JointOrientationRecognizer>

  <!-- left knee shape -->
  <JointOrientationRecognizer name="LeftKneeShapeNormal">
    <Joint name="leftKnee"/>
    <MinDegrees x="-20"/>
  </JointOrientationRecognizer>
  <JointOrientationRecognizer name="LeftKneeShapeSlightlyFlexed">
    <Joint name="leftKnee"/>
    <MaxDegrees x="-20.01"/>
    <MinDegrees x="-40"/>
  </JointOrientationRecognizer>
  <JointOrientationRecognizer name="LeftKneeShapeFlexed">
    <Joint name="leftKnee"/>
    <MaxDegrees x="-40.01"/>
  </JointOrientationRecognizer>
  
  <!-- right leg position -->
  <JointRelationRecognizer name="RightLegPositionBack">
    <Joints main="rightFoot" relative="rightHip"/>
    <MinValues z="151"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="RightLegPositionNormal">
    <Joints main="rightFoot" relative="rightHip"/>
    <MinValues z="-150"/>
    <MaxValues z="150"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="RightLegPositionForward">
    <Joints main="rightFoot" relative="rightHip"/>
    <MaxValues z="-149"/>
  </JointRelationRecognizer>

   <!--left leg position--> 
  <JointRelationRecognizer name="LeftLegPositionBack">
    <Joints main="leftFoot" relative="leftHip"/>
    <MinValues z="151"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="LeftLegPositionNormal">
    <Joints main="leftFoot" relative="leftHip"/>
    <MinValues z="-150"/>
    <MaxValues z="150"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="LeftLegPositionForward">
    <Joints main="leftFoot" relative="leftHip"/>
    <MaxValues z="-149"/>
  </JointRelationRecognizer>

</FubiRecognizers>

=== ChristianFrisson/FUBIOSC/bin/TutorialRecognizers.xml
<?xml version="1.0"?>
<!DOCTYPE FubiRecognizers SYSTEM "FubiRecognizers.dtd">
<FubiRecognizers>
  <JointRelationRecognizer name="leftHandAboveHead" visibility="hidden">
    <Joints main="leftHand" relative="head"/>
    <MinValues y="1"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="leftHandAboveShoulder" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <MinValues y="1"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="rightHandNearHead" visibility="hidden">
    <Joints main="rightHand" relative="head"/>
    <MaxValues dist="200"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="rightHandNearTorso" visibility="hidden">
    <Joints main="rightHand" relative="torso"/>
    <MaxValues dist="200"/>
  </JointRelationRecognizer>
  <JointRelationRecognizer name="leftHandAndLeftElbow" visibility="hidden">
    <Joints main="leftHand" relative="leftElbow"/>
    <MinValues y="0"/>
  </JointRelationRecognizer>
  
  <LinearMovementRecognizer name="leftHandMovesRight" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <Direction x="2" y="0" z="0"/>
    <Speed min="250"/>
  </LinearMovementRecognizer>
  <LinearMovementRecognizer name="leftHandMovesDown" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <Direction x="0" y="-2" z="0"/>
    <Speed min="250"/>
  </LinearMovementRecognizer>
  <LinearMovementRecognizer name="leftHandMovesLeft" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <Direction x="-2" y="0" z="0"/>
    <Speed min="250"/>
  </LinearMovementRecognizer>
  <LinearMovementRecognizer name="leftHandMovesUp" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <Direction x="0" y="2" z="0"/>
    <Speed min="250"/>
  </LinearMovementRecognizer>

  <!-- ************ -->
  <!-- Combinations -->
  <!-- ************ -->
  <!-- Left hand waving above head -->
  <CombinationRecognizer name="LeftHandWavingAboveHead">
    <State minDuration="0.1" maxDuration="1.2" timeForTransition="0.3">
      <Recognizer name="leftHandAboveHead"/>
      <Recognizer name="leftHandMovesLeft"/>
    </State>
    <State minDuration="0.1" maxDuration="1.2" timeForTransition="0.3">
      <Recognizer name="leftHandAboveHead"/>
      <Recognizer name="leftHandMovesRight"/>
    </State>
    <State minDuration="0.1" maxDuration="1.2" timeForTransition="0.3">
      <Recognizer name="leftHandAboveHead"/>
      <Recognizer name="leftHandMovesLeft"/>
    </State>
    <State minDuration="0.1">
      <Recognizer name="leftHandAboveHead"/>
      <Recognizer name="leftHandMovesRight"/>
    </State>
  </CombinationRecognizer>
  
   <!-- circle clockwise with left hand -->
  <CombinationRecognizer name="LeftHandCircleClockwise">
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesRight"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesDown"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesLeft"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesUp"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
  </CombinationRecognizer>
  
  <!-- simple circle anticlockwise with left hand-->
  <CombinationRecognizer name="LeftHandCircleAntiClockwise">
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesLeft"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesDown"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesRight"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="leftHandMovesUp"/>
      <NotRecognizer name="leftHandAboveShoulder"/>
    </State>
  </CombinationRecognizer>

  <!-- get left hand orientation when right hand near head-->
  <CombinationRecognizer name="LeftHandOrientation">
    <State minDuration="0.05" maxDuration="0.2" timeForTransition="0.2">
      <Recognizer name="rightHandNearHead"/>
      <Recognizer name ="leftHandAndLeftElbow"/>
    </State>
  </CombinationRecognizer>
  
</FubiRecognizers>

=== ChristianFrisson/FUBIOSC/bin/MashtaCycleRecognizers.xml
<?xml version="1.0"?>
<!DOCTYPE FubiRecognizers SYSTEM "FubiRecognizers.dtd">
<FubiRecognizers>
  <!-- Joints Recognizers -->
  <JointRelationRecognizer name="leftHandAboveHead" visibility="hidden">
    <Joints main="leftHand" relative="head"/>
    <MinValues y="1"/>
  </JointRelationRecognizer>

  <JointRelationRecognizer name="rightHandAboveShoulder" visibility="hidden">
    <Joints main="rightHand" relative="rightShoulder"/>
    <MinValues y="1"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="rightHandInFront" visibility="hidden">
    <Joints main="rightHand" relative="rightShoulder"/>
    <MaxValues z="-400"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="leftHandInFront" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <MaxValues z="-400"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="rightHandBack" visibility="hidden">
    <Joints main="rightHand" relative="rightShoulder"/>
    <MinValues z="-300"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="leftHandBack" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <MinValues z="-300"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="rightHandPointingRight" visibility="hidden">
    <Joints main="rightHand" relative="rightShoulder"/>
    <MinValues x="500"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="rightHandNearHead" visibility="hidden">
    <Joints main="rightHand" relative="head"/>
    <MaxValues dist="200"/>
  </JointRelationRecognizer>
 
  <JointRelationRecognizer name="rightHandNearLeftHand" visibility="hidden">
    <Joints main="rightHand" relative="leftHand"/>
    <MaxValues x="150" y="150" z="100"/>
    <MinValues x ="-50" y="-500" z="-100"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="rightHandNearLeftElbow" visibility="hidden">
    <Joints main="rightHand" relative="leftElbow"/>
    <MaxValues x="150" y="500" z="100"/>
    <MinValues x ="-50" y="-150" z="-100"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="LeftArmVertical" visibility="hidden">
    <Joints main="leftHand" relative="leftElbow"/>
    <MaxValues x="150" y="500" z="150"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="torsoVertical" visibility="hidden">
    <Joints main="torso" relative="neck"/>
    <MaxValues x="150" y="800" z="150"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="handsTogether" visibility="hidden">
    <Joints main="rightHand" relative="leftHand"/>
    <MaxValues dist="150"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="leftHandDown" visibility="hidden">
    <Joints main="leftHand" relative="leftHip"/>
    <MaxValues x="150" y="0" z="250"/>
    <MinValues x="-350" y="-500" z="-250"/>
  </JointRelationRecognizer>
  
  <JointRelationRecognizer name="rightHandDown" visibility="hidden">
    <Joints main="rightHand" relative="rightHip"/>
    <MaxValues x="350" y="0" z="250"/>
    <MinValues x="-150" y="-500" z="-250"/>
  </JointRelationRecognizer>
  
  <!-- Linear movement recognizers -->
  <LinearMovementRecognizer name="leftHandMovesRight" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <Direction x="2" y="0" z="0"/>
    <Speed min="250"/>
  </LinearMovementRecognizer>

  <LinearMovementRecognizer name="leftHandMovesLeft" visibility="hidden">
    <Joints main="leftHand" relative="leftShoulder"/>
    <Direction x="-2" y="0" z="0"/>
    <Speed min="250"/>
  </LinearMovementRecognizer>

  <LinearMovementRecognizer name="rightHandMovesForward" visibility="hidden">
    <Joints main="rightHand" relative="rightShoulder"/>
    <Direction x="0" y="0" z="-1"/>
   <Speed min="150"/>
  </LinearMovementRecognizer>

  <LinearMovementRecognizer name="rightHandMovesBackward" visibility="hidden">
    <Joints main="rightHand" relative="rightShoulder"/>
    <Direction x="0" y="0" z="1"/>
    <Speed min="150"/>
  </LinearMovementRecognizer>

  <!-- ************ -->
  <!-- Combinations -->
  <!-- ************ -->
  
  <!--Navigating in the map-->
  <CombinationRecognizer name="BothHandsDown">
    <State minDuration="0" maxDuration="0.03">
      <Recognizer name="torsoVertical"/>
      <Recognizer name="leftHandDown"/>
      <Recognizer name="rightHandDown"/>
    </State>
  </CombinationRecognizer>
  
  <!-- Left hand waving above head -->
  <CombinationRecognizer name="LeftHandWavingAboveHead">
    <State minDuration="0.1" maxDuration="1.2" timeForTransition="0.5">
      <Recognizer name="leftHandAboveHead"/>
      <Recognizer name="leftHandMovesLeft"/>
    </State>
    <State minDuration="0.1">
      <Recognizer name="leftHandAboveHead"/>
      <Recognizer name="leftHandMovesRight"/>
    </State>
  </CombinationRecognizer>

  <!-- right hand pushing -->
  <CombinationRecognizer name="RightHandPushAboveShoulder">
    <State minDuration="0.1" maxDuration="0.8" timeForTransition="0.4">
      <Recognizer name="rightHandAboveShoulder"/>
      <Recognizer name ="rightHandMovesForward"/>
	  <NotRecognizer name="rightHandNearHead"/>
    </State>
    <State minDuration="0.3" maxDuration="1.8" timeForTransition="0.2">
      <Recognizer name="rightHandAboveShoulder"/>
	    <NotRecognizer name="rightHandBack"/>
    </State>
    <State minDuration="0.1">
      <Recognizer name="rightHandAboveShoulder"/>
      <Recognizer name="rightHandMovesBackward"/>
	  <NotRecognizer name="rightHandNearHead"/>
    </State>
  </CombinationRecognizer>

  <!-- right hand position relative to left arm -->
  <CombinationRecognizer name="RightHandNearLeftArm">
    <State minDuration="0.03" maxDuration="0.06">
      <Recognizer name="rightHandNearLeftHand"/>
      <Recognizer name ="LeftArmVertical"/>
      <Recognizer name="leftHandBack"/>
      <AlternativeRecognizers>
        <Recognizer name="rightHandNearLeftElbow"/>
        <Recognizer name="LeftArmVertical"/>
        <Recognizer name="leftHandBack"/>
      </AlternativeRecognizers>
    </State>
  </CombinationRecognizer>

  <!-- get left hand orientation when right hand pointing right-->
  <CombinationRecognizer name="LeftHandOrientation3">
    <State minDuration="0.03" maxDuration="0.06">
      <Recognizer name="rightHandPointingRight"/>
      <NotRecognizer name="rightHandInFront"/>
      <NotRecognizer name ="rightHandAboveShoulder"/>
      <NotRecognizer name ="leftHandInFront"/>
    </State>
  </CombinationRecognizer>

  <!--right hand near pocket and left arm scanning-->
  <CombinationRecognizer name="LeftHandScanning">
    <State minDuration="0.03" maxDuration="0.06">
      <Recognizer name="rightHandDown"/>
      <Recognizer name="leftHandInFront"/>
      <NotRecognizer name="leftHandDown"/>
    </State>
  </CombinationRecognizer>

  <!--Control parameter with vertical or
      horizontal distance between hands-->
  <CombinationRecognizer name="BothHandsInFront">
    <State minDuration="0.03" maxDuration="0.06">
      <Recognizer name="rightHandInFront"/>
      <Recognizer name="leftHandInFront"/>
      <NotRecognizer name ="leftHandDown"/>
    </State>
  </CombinationRecognizer>

  <!-- right hand near head and left hand down-->
  <CombinationRecognizer name="RightHandNearHead">
    <State minDuration="0.1" maxDuration="0.2">
      <Recognizer name="rightHandNearHead"/>
      <Recognizer name="leftHandDown"/>
    </State>
  </CombinationRecognizer>
</FubiRecognizers>
